[tool.poetry]
name = "guru-pam"
version = "0.1.0"
description = ""
authors = ["dutchrover <ken@kwvcompany.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
